[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "jira-helper"
version = "1.0.0"
description = "A Jira helper MCP server"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "MCP Server Team", email = "example@example.com"},
]
dependencies = [
    "python-dotenv>=1.0.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.22.0",
    "pydantic>=2.0.0",
    "requests>=2.32.4",
    "sse-starlette>=2.4.1",
    "rich>=14.1.0",
    "typer>=0.16.0",
    "atlassian-python-api>=4.0.4",
    "PyYAML>=6.0.1",
    "mcp"
]

[project.scripts]
jira-helper = "main:app"

[tool.setuptools.packages.find]
where = ["src"]
