[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "jira-helper"
version = "0.1.0"
description = "A Jira helper MCP server"
readme = "README.md"
requires-python = ">=3.11"
authors = [
    {name = "MCP Server Team", email = "example@example.com"},
]
dependencies = [
    "python-dotenv>=1.0.0",
    "fastapi>=0.100.0",
    "uvicorn>=0.22.0",
    "pydantic>=2.0.0",
    "requests>=2.31.0",
    "sse-starlette>=1.6.5",
    "rich>=13.0.0",
    "typer>=0.9.0",
    "jira>=3.5.2",
    "PyYAML>=6.0.1"
]

[project.scripts]
jira-helper = "src.main:app"

[tool.hatch.build.targets.wheel]
packages = ["src"]
