[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mcp-manager"
version = "0.1.0"
description = "Comprehensive manager for MCP servers"
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "MCP Server Team", email = "example@example.com"},
]
dependencies = [
    "typer>=0.9.0",           # CLI framework
    "pydantic>=2.11.3",       # Data validation
    "rich>=13.7.0",           # Rich text and formatting
    "virtualenv>=20.25.0",    # Virtual environment management
    "jinja2>=3.1.3",          # Template rendering
    "httpx>=0.28.1",          # HTTP client for testing connections
]

[project.scripts]
mcp-manager = "mcp_manager.cli:app"

[tool.hatch.build.targets.wheel]
packages = ["src/mcp_manager"]
